import { Opportunity } from '../types';

export const VERIFIED_LIVE_2026_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'live-wetech-conf-2026',
    title: 'Wetech Annual Conference & Career Expo 2026',
    organization: 'Wetech (Women in Technology)',
    type: 'conference',
    description:
      'Premier gathering of women in tech, builders, early-career engineers, and leaders across Africa. Features live recruitment booths, technical workshops in frontend, cloud, and AI, portfolio reviews, and venture pitches.',
    eligibility: 'Open to women and non-binary tech builders, university candidates, early-career engineers, career transitioners, and ally supporters across Africa.',
    location: 'Lagos, Nigeria (Hybrid)',
    remote: true,
    deadline: '2026-08-30',
    skills: ['Networking', 'Career Readiness', 'React', 'Frontend', 'Cloud', 'AI/ML'],
    career_level: ['student', 'recent_graduate', 'early_career', 'career_switcher', 'intermediate'],
    education_level: ['bootcamp', 'self_taught', 'undergraduate', 'university', 'graduate', 'any'],
    country_requirement: ['Nigeria', 'Pan-Africa', 'Global'],
    field: 'Technology & Software Engineering',
    funding_or_prize: 'Free student passes & Career booth access',
    application_url: 'https://wetechng.com/conference',
    source_url: 'https://wetechng.com',
    status: 'verified',
    community_id: 'comm-wetech',
  },
  {
    id: 'live-moonshot-techcabal-2026',
    title: 'Moonshot by TechCabal 2026: The Premier African Tech Conference',
    organization: 'TechCabal',
    type: 'conference',
    description:
      'Flagship conference converging tech founders, engineers, VC investors, and ecosystem operators across the continent. Features hands-on dev sessions, product keynotes, and student/early-career tickets.',
    eligibility: 'Founders, software engineers, product designers, data practitioners, students, and tech enthusiasts building for Africa.',
    location: 'Eko Convention Centre, Lagos, Nigeria',
    remote: false,
    deadline: '2026-09-15',
    skills: ['Tech Innovation', 'Software Architecture', 'Ecosystem Strategy', 'Product Engineering'],
    career_level: ['student', 'recent_graduate', 'early_career', 'intermediate', 'experienced'],
    education_level: ['any'],
    country_requirement: ['Nigeria', 'Pan-Africa', 'Global'],
    field: 'Ecosystem & Emerging Tech',
    funding_or_prize: 'Startup Pitch Prizes & Subsidized Early-Career Tickets',
    application_url: 'https://moonshot.techcabal.com',
    source_url: 'https://techcabal.com/moonshot',
    status: 'verified',
  },
  {
    id: 'live-google-io-lagos-2026',
    title: 'Google I/O Extended Lagos 2026',
    organization: 'Google Developer Groups Lagos',
    type: 'conference',
    description:
      'The largest community-led developer event in Sub-Saharan Africa celebrating Google technology announcements, Android, Gemini AI, Web Standards, and Cloud architecture.',
    eligibility: 'Developers, software engineers, UI designers, and students interested in Google technology and open web standards.',
    location: 'Landmark Event Centre, Lagos, Nigeria',
    remote: true,
    deadline: '2026-06-20',
    skills: ['Android', 'Web Development', 'Gemini AI', 'Cloud Architecture', 'TypeScript'],
    career_level: ['student', 'recent_graduate', 'early_career', 'beginner', 'intermediate'],
    education_level: ['any'],
    country_requirement: ['Nigeria', 'Africa'],
    field: 'Google Technologies, Web & AI',
    funding_or_prize: 'Free Community Pass & Swag',
    application_url: 'https://gdg.community.dev/gdg-lagos',
    source_url: 'https://gdg.community.dev',
    status: 'verified',
  },
  {
    id: 'live-datafest-africa-2026',
    title: 'DataFest Africa 2026: Data, AI & Machine Learning Summit',
    organization: 'DataFest Africa',
    type: 'conference',
    description:
      'High-impact annual conference connecting thousands of data scientists, machine learning engineers, and tech talents with masterclasses and hiring partner panels.',
    eligibility: 'Data analysts, data scientists, ML engineers, software developers, and students wanting to work in AI and data.',
    location: 'Lagos, Nigeria & Virtual Stream',
    remote: true,
    deadline: '2026-09-28',
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'SQL', 'Deep Learning'],
    career_level: ['student', 'recent_graduate', 'early_career', 'intermediate'],
    education_level: ['any'],
    country_requirement: ['Nigeria', 'Pan-Africa', 'Global'],
    field: 'Data Science & Artificial Intelligence',
    funding_or_prize: 'Datathon Hackathon Prizes & Hiring Showcase',
    application_url: 'https://datafestafrica.com',
    source_url: 'https://datafestafrica.com',
    status: 'verified',
  },
  {
    id: 'live-nexascale-cohort-2026',
    title: 'Nexascale Cloud & DevOps Hands-On Cohort 2026',
    organization: 'Nexascale',
    type: 'fellowship',
    description:
      'A structured 12-week program enabling early-career and career-transitioning tech professionals to build production-grade cloud, DevOps, and backend projects.',
    eligibility: 'Open to self-taught developers, recent graduates, and early-career software developers across Africa looking to gain real-world project experience.',
    location: 'Virtual / Africa',
    remote: true,
    deadline: '2026-05-15',
    skills: ['Cloud Computing', 'Docker', 'DevOps', 'CI/CD', 'Linux', 'Git'],
    career_level: ['beginner', 'recent_graduate', 'early_career', 'career_switcher'],
    education_level: ['any'],
    country_requirement: ['Pan-Africa'],
    field: 'Cloud Infrastructure & DevOps',
    funding_or_prize: 'Full Tuition Scholarship & Mentorship',
    application_url: 'https://nexascale.org/programs',
    source_url: 'https://nexascale.org',
    status: 'verified',
    community_id: 'comm-nexascale',
  },
];
